.ddev/docker-compose.vite.yaml, composer.json, composer.lock, config/project/project.yaml
In preparation for migrating over the data for blog posts and projects, I've installed the Feed Me plugin. 
Also saw a deprecation warning for the `version`-tag in the docker-compose file and remove it.
=> [chore] install feed me plugin

composer.json, composer.lock, config/project/project.yaml, templates/blog/index.twig
Nothing crazy, I just changed the pagination on the blog posts index page from 6 to 15 for now, so we can QA the imported data a bit faster. Also updated some plugins.
=> [feature] change blog posts pagination from 6 to 15 for now

config/project/project.yaml
Setup the system email configuration, by adding the respective SMTP environmental variables. The actual values were already added to Fortrabbit.
=> [feature] setup system email config

src/css/main.css
This PR fixes a linting formatting error.
=> Fix linting error

src/css/main.css, templates/404.twig, templates/_layouts/layout.twig, templates/_modules/blocks/newsletter.twig, templates/_modules/footer.twig, templates/_modules/header.twig, templates/_modules/lang-switch.twig, templates/_modules/pagination.twig, templates/_partials/entry/article.twig, templates/_partials/entry/project.twig, templates/_rich-text/simple.twig, templates/blog/_entry.twig, templates/blog/_modules/overview-page.twig, templates/events/index.twig, templates/generic/_entry.twig, templates/index.twig, templates/projects/_entry.twig, templates/projects/index.twig
This PR:
- Removes unused Tailwind text sizes and colors
- Adds additional gray colors
- Adds richtext "simple" for richtext fields
- Removes `px` based custom variants, in favour of `rem`
=> [chore] general clean up

config/project/entryTypes/eventsIndex--1a0ed17a-7208-4b7e-894f-64506d5432d6.yaml, config/project/entryTypes/genericPage--eec7038e-53af-4299-bf11-db14e0fbd073.yaml, config/project/entryTypes/projectsIndex--7eb26dd5-1c10-45d1-a16b-85a148e4bf8a.yaml, config/project/project.yaml, templates/events/index.twig, templates/generic/_entry.twig, templates/projects/index.twig
This PR adds the header related fields to the events Index, generic pages and projects index.
=> Add header to sections

composer.json, composer.lock, config/project/project.yaml
Critical Craft update: https://github.com/prototypefund/ptf-site/security/dependabot/4 
And I also updated the other plugins while I was at it.
=> [chore] update Craft and plugins

templates/projects/index.twig
This PR removes the project sticky filter and ignore "p" param.
=> [chore] Remove project sticky filter and ignore "p" param

templates/projects/index.twig
This PR adds the categories conditional.
=> Add categories conditional

templates/_modules/newsletter-form.twig
This PR changes the newsletter border color.
=> [fix] change newsletter border color

templates/projects/index.twig
This PR changes the filter logic.
=> Change filter logic

src/css/main.css, templates/_modules/header.twig, templates/projects/_modules/checkbox-filter.twig, templates/projects/index.twig, translations/de/site.php
This PR adds the header design tweaks and changes a translation.
=> [chore] add header design tweaks and change translation

src/js/components/main-nav.ts, templates/_modules/main-nav.twig
This PR adds border animations to the nav link hover state.
=> [chore] add nav link hover state

templates/_modules/main-nav.twig, templates/_partials/entry/quote.twig, templates/_partials/entry/sideHeadingText.twig, templates/_rich-text/standard.twig, templates/blog/_entry.twig, templates/projects/_entry.twig
This PR resolves a project page retcon error and refactors Tailwind [px] values
=> [fix] resolve project page retcon error and refactor Tailwind [px] values

config/project/ckeditor/configs/9a1aea15-6b42-4b96-b047-ee412bfabc78.yaml, config/project/fields/intro--ad1324f8-1337-475f-8516-ab1e13543027.yaml, config/project/fields/nextReads--9c0f58c4-4b28-4aca-b80d-3b370bc38f9e.yaml, config/project/project.yaml, templates/_rich-text/intro.twig
This PR increases the next read items and add intro highlight.
=> Increase next read items and add intro highlight

templates/_rich-text/standard.twig, templates/blog/_entry.twig, templates/blog/_modules/next-reads.twig, translations/de/site.php
This PR adds a "See all" link.
=> [chore] add “See all” link

templates/blog/_modules/overview-page.twig
This PR adds an "All Articles" filter to the blog filter.
=> [chore] add “all articles” filter to blog filter

templates/_modules/main-nav.twig
This PR adds further `isActive` logic for active links in the main nav.
=> [chore] add main nav isActive logic for active links

templates/_modules/arrow-link.twig
This PR increases the arrow link gap.
=> [chore] increase arrow link gap

templates/_rich-text/columns.twig
This PR removes the col-xs-24 div.
=> [chore] remove col-xs-24 div

templates/_modules/blocks/cta-banner.twig
This PR adds a CTA Banner background default.
=> [fix] add CTA Banner background default

config/project/fields/articleAuthor--6c3461da-2d32-418a-803b-efe329a38c30.yaml, config/project/project.yaml, config/project/sections/authors--a6babdad-fc37-48fb-ac86-088ea4129e1e.yaml, src/css/main.css, templates/_modules/next-reads.twig, templates/projects/_modules/next-reads.twig, translations/de/site.php, web/static/images/patterns/bg-pattern-br-light-blue.svg, web/static/images/patterns/bg-pattern-br-sky-blue.svg, web/static/images/patterns/bg-pattern-newsletter.svg, web/static/images/patterns/bg-pattern-tl-light-blue.svg, web/static/images/patterns/bg-pattern-tl-sky-blue.svg, web/static/images/patterns/bg-pattern-tr-light-blue.svg, web/static/images/patterns/bg-pattern-tr-sky-blue.svg
This PR adds related project logic, translation changes and updated colors.
=> [chore] add related project logic, translation changes and updated colors

config/project/entryTypes/author--f6ed0d5d-4ab8-418b-801e-b11f6cb309a5.yaml, config/project/entryTypes/juror--2b8e8081-de20-479d-a37d-362dded4c944.yaml, config/project/entryTypes/peopleGrid--8760f57d-c660-4b7c-a052-940ebce3408c.yaml, config/project/entryTypes/teamMember--4f4c5206-4b19-4476-ad5a-331b92869abd.yaml, config/project/fields/articleAuthor--6c3461da-2d32-418a-803b-efe329a38c30.yaml, config/project/fields/email--7601873a-7197-47a0-9e66-c07512a11dd2.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/fields/people--65bbee3d-0a45-412f-a8e5-04ee7c01d8af.yaml, config/project/fields/role--36d3151d-99ef-4672-9521-82f0e9b0646d.yaml, config/project/fields/website--7bb4d517-5179-42f5-a2b7-0400280d5411.yaml, config/project/imageTransforms/avatarLarge--c32d4850-8999-46e0-aad2-c43b9d69e8bd.yaml, config/project/project.yaml, config/project/sections/jury--9b03faaf-18e7-4df7-b87c-282d1ead8ea3.yaml, config/project/sections/team--a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c.yaml, templates/_modules/blocks/people-grid.twig, templates/_modules/headers/project.twig, templates/_modules/link-list.twig, templates/_modules/modules.twig, templates/_modules/person-info.twig, templates/_rich-text/simple.twig, templates/blog/_entry.twig, translations/de/site.php
=> [feature] add people grid

config/project/entryTypes/peopleGrid--8760f57d-c660-4b7c-a052-940ebce3408c.yaml, config/project/entryTypes/relatedCtaBanner--b2b9ea1c-a462-4794-bd6c-d9700c56f94c.yaml, config/project/project.yaml, templates/_modules/blocks/people-grid.twig, translations/de/site.php
This PR adds people grid tweaks.
=> [chore] add people grid tweaks

config/matrix-extended.php, config/project/entryTypes/step--c84399c0-dd2f-498b-adbf-528b801843c4.yaml, config/project/entryTypes/steps--72564f6d-cb4e-40a8-b30c-99153000f278.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/fields/stepText--d94ae721-befb-4d87-921e-3152926fdd9e.yaml, config/project/fields/steps--4ca0ade4-44d2-4594-8253-a909b0a44bb2.yaml, config/project/fields/stepsText--03cbee0a-9ed8-464b-ae01-b638102841b4.yaml, config/project/project.yaml, templates/_modules/blocks/steps.twig, templates/_modules/modules.twig
=> [chore] add steps block

src/css/main.css
This PR moves `@view-transition` into `@layer base`.
=> [chore] move view transition into layer baser

src/css/main.css
This PR moves the `@view-transition`.
=> [chore] move view transition

config/matrix-extended.php, config/project/entryTypes/faq--ced3c245-d70a-43bb-a15b-37fa5292066b.yaml, config/project/entryTypes/relatedFaqs--17844487-59d2-4434-a5f4-3030d625da70.yaml, config/project/fields/faqs--052db112-993d-44ef-bb78-bfa504e8d2e0.yaml, config/project/fields/genericLink--eb089684-4134-4cd9-a60d-4aaac63db8f4.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/project.yaml, config/project/sections/faqs--a805834b-57ba-4e15-8082-a5bf2c23d495.yaml, src/css/main.css, templates/_modules/blocks/faqs.twig, templates/_modules/modules.twig, templates/_modules/side-heading.twig, templates/_partials/entry/embed.twig, templates/_partials/entry/sideHeadingText.twig, templates/_rich-text/columns.twig, templates/blog/_entry.twig, templates/trends/_entry.twig
=> [feature] add FAQs

config/matrix-extended.php, config/project/entryTypes/expandableText--17844487-59d2-4434-a5f4-3030d625da70.yaml, config/project/entryTypes/phase--f379a383-dc25-494c-a93c-bd79b34bce36.yaml, config/project/entryTypes/timeline--e52cab12-65a2-4958-badf-d0b2f39913d0.yaml, config/project/fields/dates--a6825d2c-f661-4fd6-ac6e-b7b06cf823ab.yaml, config/project/fields/expandableItems--052db112-993d-44ef-bb78-bfa504e8d2e0.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/fields/phaseText--747e573a-dea9-419c-9f81-e1778c7f1b13.yaml, config/project/fields/phases--f190999c-96f7-4cfe-900b-d5f76f8e8018.yaml, config/project/project.yaml, config/project/sections/timelines--f1478917-bc75-4118-b7d9-7cd5fdae8872.yaml, templates/_modules/blocks/expandable-text.twig, templates/_modules/headers/article.twig, templates/_modules/modules.twig, templates/_rich-text/standard.twig
This PR adds the timeline module.
=> [feature] add timeline

templates/_modules/blocks/expandable-text.twig
This PR adds the `details` element.
=> [chore] add details element

templates/_modules/blocks/link-list.twig
This PR adds a link list subheading.
=> [chore] add link list subheading

templates/_modules/headers/simple.twig
This PR changes the newsletter text color.
=> [chore] change newsletter text color

config/project/fields/stepText--d94ae721-befb-4d87-921e-3152926fdd9e.yaml, config/project/project.yaml
This PR changes the steps count.
=> [chore] change steps count

templates/_modules/blocks/link-list.twig
This PR increases the link list line height.
=> [chore] increase link list line height

config/project/entryTypes/basicTextPage--bc05e7ef-ab74-4604-95d9-d14a383ad33a.yaml, config/project/fields/headerBackground--62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8.yaml, config/project/project.yaml, config/project/sections/genericPages--6e040108-27cc-4a4a-bca9-c5e3ab1bdc04.yaml, src/css/main.css, templates/_modules/headers/simple.twig, templates/blog/_entry.twig, templates/generic/_entry.twig, templates/trends/_entry.twig, web/static/images/patterns/bg-pattern-br-gray-4.svg, web/static/images/patterns/bg-pattern-tl-gray.svg, web/static/images/patterns/bg-pattern-tr-gray.svg
This PR adds a simple text page.
=> [chore] add simple text page

templates/_modules/blocks/newsletter.twig, web/static/images/patterns/bg-pattern-newsletter.svg
This PR updates the newsletter colors.
=> [chore] update newsletter colors

config/matrix-extended.php, config/project/entryTypes/genericTeaser--3445dc73-731c-4dd7-90f6-bc2e1d87679d.yaml, config/project/entryTypes/genericTeasers--ca7069c8-f9a4-44e7-9b3e-21db114e4134.yaml, config/project/entryTypes/statement--8ad973e9-d5d2-4385-b6cf-beb0a9ca03d2.yaml, config/project/fields/genericTeasers--78bf584a-2694-4dae-bbd5-5e5ba72a5d92.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/project.yaml, templates/_modules/blocks/blog-teasers.twig, templates/_modules/blocks/generic-teasers.twig, templates/_modules/blocks/project-teasers.twig, templates/_modules/blocks/statement.twig, templates/_modules/blocks/trend-teasers.twig, templates/_modules/modules.twig, templates/_modules/next-reads.twig, templates/blog/_modules/next-reads.twig, templates/projects/_modules/next-reads.twig
This PR adds the generic page teaser and statement modules.
=> [feature] Add generic page teaser and statement modules

config/project/entryTypes/project--af427185-4826-4e80-bd57-096797b92f4b.yaml, config/project/project.yaml, templates/_modules/headers/project.twig, templates/_partials/entry/project.twig, templates/projects/_entry.twig
This PR removes the claim field.
=> [chore] remove claim field

config/project/fields/articleAuthor--6c3461da-2d32-418a-803b-efe329a38c30.yaml, config/project/fields/people--65bbee3d-0a45-412f-a8e5-04ee7c01d8af.yaml, config/project/project.yaml, templates/_modules/blocks/people-grid.twig
This PR allows only authors to be article creators, alongside remove the **website** field from the person (author, juror, team member) button links.
=> [chore] allow only authors article creators

config/project/categoryGroups/blogCategories--bdc78be0-ab3b-4c52-9657-0eaaff1208e9.yaml, config/project/categoryGroups/projectRounds--a06eff6a-35ff-45b1-9c02-c6ef2f3f948c.yaml, config/project/categoryGroups/projectTechnologies--8d8e3436-a20e-4222-a530-d52fa736ae4d.yaml, config/project/categoryGroups/projectTopics--c63194ff-c47c-4c20-80b1-39bfedfc3b0f.yaml, config/project/categoryGroups/projectYearGroups--5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a.yaml, config/project/entryTypes/basicTextPage--bc05e7ef-ab74-4604-95d9-d14a383ad33a.yaml, config/project/entryTypes/blogIndex--2b86894c-5b98-44d4-8ed6-88b2c8b5e601.yaml, config/project/entryTypes/eventsIndex--1a0ed17a-7208-4b7e-894f-64506d5432d6.yaml, config/project/entryTypes/genericPage--eec7038e-53af-4299-bf11-db14e0fbd073.yaml, config/project/entryTypes/newsletterPage--16d093d2-5427-4466-a013-a3620b62ef69.yaml, config/project/entryTypes/projectsIndex--7eb26dd5-1c10-45d1-a16b-85a148e4bf8a.yaml, config/project/entryTypes/trendsIndex--81982550-63ea-49d9-9142-e30783a4fd54.yaml, config/project/fields/secondaryText--f1944b34-730a-4bbe-8a1b-33fe56c07107.yaml, config/project/project.yaml, templates/_modules/headers/simple.twig, templates/blog/_modules/overview-page.twig, templates/events/index.twig, templates/generic/_entry.twig, templates/newsletter/index.twig, templates/projects/_category.twig, templates/projects/index.twig, templates/trends/index.twig
This PR adds a secondary text field.
=> [chore] add secondary text

config/project/entryTypes/application--994e9c1d-7448-4401-bdc6-2657748b1205.yaml, config/project/fields/amount--8a2262ef-cde3-425f-a9a4-4f531b781c31.yaml, config/project/fields/applicationText--992e8da2-9620-4ec5-a2d5-2f8b3c2c23e6.yaml, config/project/fields/date--abb2edcb-afed-4766-9c25-594bf7d42262.yaml, config/project/project.yaml, config/project/sections/application--db229da2-7471-4db0-a3ec-697da49531d1.yaml, src/css/main.css, templates/_modules/phase.twig, templates/application/index.twig
This PR adds the application page.
=> [feature] add application page

config/project/project.yaml, config/project/users/groups/editors--01991296-4d23-4e54-8e00-2f61d7a524c8.yaml, config/project/users/users.yaml
This PR adds the user editor group.
=> [chore] add user editor group

templates/_modules/blocks/publications.twig
This PR fixes the width for publications thumbnails.
=> [fix] fix width for publications thumbnails

config/project/fields/phaseText--747e573a-dea9-419c-9f81-e1778c7f1b13.yaml, config/project/project.yaml
This PR makes the the phase text field translatable.
=> [chore] make phase text translatable

config/matrix-extended.php, config/project/entryTypes/event--ac14f0ca-4155-4f2f-ad58-f2648062e062.yaml, config/project/entryTypes/eventTeasers--4bfc6f18-1241-4dd1-be73-a95290f1a887.yaml, config/project/entryTypes/relatedTimeline--e3e7a426-21c5-4767-b047-739432c7f60a.yaml, config/project/entryTypes/timeline--e52cab12-65a2-4958-badf-d0b2f39913d0.yaml, config/project/fields/eventNextReads--5f79b151-95c9-4cad-be78-175d28cb5d10.yaml, config/project/fields/location--6da63526-25ff-45c2-b4f7-543c359ec775.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/fields/time--d9abc0f0-98c8-45d7-aa77-d9f8fbe83f7a.yaml, config/project/fields/timeline--398a9144-4479-4781-9453-19c376cc6763.yaml, config/project/project.yaml, config/project/sections/events--6faac0be-91b5-4747-95b9-2157c66c6246.yaml, templates/_modules/blocks/blog-teasers.twig, templates/_modules/blocks/event-teasers.twig, templates/_modules/blocks/expandable-text.twig, templates/_modules/blocks/generic-teasers.twig, templates/_modules/blocks/timeline.twig, templates/_modules/blocks/trend-teasers.twig, templates/_modules/date-time.twig, templates/_modules/headers/article.twig, templates/_modules/headers/image.twig, templates/_modules/main-nav.twig, templates/_modules/modules.twig, templates/_modules/timeline.twig, templates/_partials/entry/event.twig, templates/blog/_entry.twig, templates/events/_entry.twig, templates/events/_modules/next-reads.twig, templates/events/_modules/teasers-list.twig, translations/de/site.php
=> [feature] Add event page

config/matrix-extended.php, config/project/entryTypes/textGrid--acfeb71e-c3fa-40d8-8b68-3fa03b22cf0a.yaml, config/project/entryTypes/textRow--7cd0ec40-65a3-4af3-9c73-edd6ac3d4b12.yaml, config/project/fields/announcementText--d7dfca16-25e6-43de-8bf1-4afdf802a486.yaml, config/project/fields/columns--15140d29-2c87-492e-84f4-90eb738eb0d8.yaml, config/project/fields/enableAnnouncementBar--e0be08b6-634c-4eed-aa9a-175b6bc828c1.yaml, config/project/fields/modules--1bf40018-82e4-4e44-bbd6-6f49c132678d.yaml, config/project/fields/rows--d7c13ef6-9822-4fd8-83f3-ddcd61ea3184.yaml, config/project/globalSets/announcementBar--7b3aeb54-f11e-44f1-baf0-a1a5182e0967.yaml, config/project/globalSets/fonts--137c86ac-e143-4792-b936-38c41302eccd.yaml, config/project/project.yaml, templates/_layouts/layout.twig, templates/_modules/announcement-bar.twig, templates/_modules/blocks/text-grid.twig, templates/_modules/modules.twig, templates/_rich-text/standard.twig
This PR adds a new text grid module and announcment bar.
=> [feature] add text grid and announcment bar

config/project/entryTypes/eventsIndex--1a0ed17a-7208-4b7e-894f-64506d5432d6.yaml, config/project/project.yaml
This PR reduces the modules size in the Events Index page.
=> [chore] reduce modules size in Events Index page

config/project/entryTypes/pastEventsIndex--35a4b3c3-5eef-4146-8fcc-2652e9582ec4.yaml, config/project/entryTypes/talk--0a7d996f-dc9c-416e-ab72-2d475eaa550b.yaml, config/project/fields/spakers--c5f55fcf-63a3-46ab-8990-2d967de34b7d.yaml, config/project/project.yaml, config/project/sections/pastEventsIndex--80923105-ebb3-433d-ab36-1026a9f76aea.yaml, config/project/sections/talks--8e8c94a1-92b5-4b37-84ed-670e13da4f61.yaml, templates/_modules/main-nav.twig, templates/events/_past.twig, templates/events/index.twig
This PR adds events, past events and talks.
=> [feature] add events, past events and talks

config/project/entryTypes/barChart--1d4b8eb8-ee07-4f5c-971c-4b05e58b7d9c.yaml, config/project/entryTypes/charts--62872793-9d0f-4ffe-a713-748f5c9c6605.yaml, config/project/fields/charts--17aa749c-756b-4767-9e7e-7368078c7494.yaml, config/project/fields/data--62bd293d-8f1c-49bc-bd74-5fc98d9eefba.yaml, config/project/fields/text--0b9eb562-64e5-4b3c-9478-8cefd24e8039.yaml, config/project/project.yaml, config/project/sections/barCharts--e84ef096-91d0-41ed-8a5c-6afffcfc2ed6.yaml, package-lock.json, package.json, src/js/components/bar-chart.tsx, src/js/main.js, templates/_modules/blocks/expandable-text.twig, templates/_partials/entry/charts.twig, tsconfig.json
This PR adds the recharts chart partial
=> [feature] add chart partial

config/project/entryTypes/homepage--711863fc-e341-4c43-b45b-dc33dc3c9c2b.yaml, config/project/project.yaml, templates/index.twig
This PR adds modules to the homepage.
=> [chore] add modules to homepage

templates/feed.rss.twig
This PR fixes the main image in the blog RSS feed, which was still based on the old structure and eager loading.
=> [fix] rss feed main image

config/project/fields/teaserText--15f1ebd8-2e95-45e1-81f5-d39b6253762e.yaml, config/project/project.yaml
This PR makes the statement fields translatable.
=> [chore] Make statement fields translatable

config/project/fields/columns--15140d29-2c87-492e-84f4-90eb738eb0d8.yaml, config/project/project.yaml
This PR makes the columns field translatable.
=> [chore] make columns field translatable

templates/_modules/headers/project.twig
This PR checks for nulls in project links.
=> [fix] check for nulls in project links

config/project/entryTypes/newsletterPage--16d093d2-5427-4466-a013-a3620b62ef69.yaml, config/project/project.yaml, templates/_modules/blocks/link-list.twig, templates/_modules/blocks/newsletter.twig, templates/newsletter/index.twig, translations/de/site.php
This PR adds newsletter fields.
=> [chore] add newsletter fields

config/matrix-extended.php
This PR moves the Generic Teasers into the Teasers group.
=> [chore] move generic teasers into teasers group

templates/blog/_entry.twig
This PR fixes the blog post date.
=> [fix] fix blog post date

composer.json, composer.lock, config/project/project.yaml
=> [chore] update Craft

templates/projects/_entry.twig
This PR resolves the issue with in funding rendering the current date.
=> [fix] resolve in funding rendering current date

templates/blog/_entry.twig, templates/projects/_entry.twig
This PR moves the article and project modules.
=> [chore] move modules

templates/_modules/blocks/link-list.twig, templates/_modules/blocks/publications.twig, templates/_modules/next-reads.twig
This PR changes the `max-width` to 40% on various headings.
=> [chore] change max-width to 40%

templates/_layouts/layout.twig, templates/_modules/announcement-bar.twig, templates/_modules/blocks/newsletter.twig, templates/_modules/button.twig, templates/_modules/filters.twig, templates/_modules/footer.twig, templates/_modules/headers/image.twig, templates/_modules/headers/project.twig, templates/_modules/headers/simple.twig, templates/_modules/lang-switch.twig, templates/_modules/main-nav.twig, templates/_modules/newsletter-form.twig, templates/_partials/entry/article.twig, templates/blog/_modules/overview-page.twig, templates/projects/_category.twig
This PR is another round of design polishing.
=> [chore] design polishing

config/project/entryTypes/newsletterIndex--16d093d2-5427-4466-a013-a3620b62ef69.yaml, config/project/entryTypes/searchIndex--5dbb535e-8ef1-46d6-8af1-f389d054afdf.yaml, config/project/entryTypes/yearGroupsIndex--8042936f-727d-4d5e-a1ae-0db7cabde8a8.yaml, config/project/project.yaml, config/project/sections/searchIndex--74b62005-8687-4f36-bcd6-d5d1b601bf41.yaml, config/project/sections/yearGroupsIndex--df79da8e-b2be-4260-b680-71ef777426bf.yaml, templates/_modules/search.twig, templates/projects/_entry.twig, templates/year-groups/index.twig
This feature adds year groups.
=> [feature] add year groups

templates/_modules/cohorts.twig, templates/rounds/index.twig, templates/year-groups/_category.twig, templates/year-groups/index.twig
This PR adds cohort pagination.
=> [chore] add cohort pagination

templates/_modules/cohorts.twig
This PR adds the generic link to the cohort.
=> [chore] add generic link

templates/_modules/main-nav.twig
This PR adds a active nav link for trends when on a trend page.
=> [chore] add nav trends highlight

templates/_modules/display-toggle.twig, templates/_modules/headers/simple.twig, templates/_modules/input-text.twig, templates/_rich-text/intro.twig, templates/_rich-text/standard.twig
This PR adds dark mode polishing.
=> [chore] dark mode polishing

templates/feed.twig
This PR removes the RSS testing output.
=> [chore] remove RSS testing

config/project/imageTransforms/w1200--504f909d-20af-4a66-b4a5-46c966689b30.yaml, config/project/imageTransforms/w1200__3_2--b679179f-230c-44d5-a29d-2858d82c9ecd.yaml, config/project/imageTransforms/w1200__4_3--646fed4b-fc85-4ed3-8082-aace0ad37228.yaml, config/project/imageTransforms/w1200__5_4--d4c24b33-4a46-4c55-980e-c1d4af12f9bf.yaml, config/project/imageTransforms/w1600__3_2--aa5a4279-2914-491e-8808-8010bd65fbf9.yaml, config/project/imageTransforms/w1600__4_3--7e9e1e86-3f4e-4d20-850c-19e356949194.yaml, config/project/imageTransforms/w1600__5_4--c94fde1d-e39d-42fe-b771-7e2a22535e6c.yaml, config/project/imageTransforms/w2000--91a7ad8a-d35b-4738-b71b-a18f899afc5d.yaml, config/project/imageTransforms/w2000__3_2--4014ee8b-e895-4a22-a40b-ddece7bb3bcc.yaml, config/project/imageTransforms/w2000__4_3--5bc4069a-ab98-412d-b924-e02887e903b3.yaml, config/project/imageTransforms/w2000__5_4--b46f826b-dfdb-409c-b483-08cf751ab744.yaml, config/project/imageTransforms/w300--8d4ed15c-dd0c-4e96-ae25-ff97b2b6bf03.yaml, config/project/imageTransforms/w800--586087db-4dd7-43ba-929b-b3f7cef02ff8.yaml, config/project/imageTransforms/w800__3_2--bf0cda56-d723-4b47-898e-f74730a328b2.yaml, config/project/imageTransforms/w800__4_3--67b4e70e-1a4a-49b5-ab41-3f48a1b32513.yaml, config/project/imageTransforms/w800__5_4--2dae0a42-be0f-40ca-bddb-0d02be719e26.yaml, config/project/project.yaml, templates/_macros.twig, templates/_modules/blocks/generic-teasers.twig, templates/_modules/blocks/people-grid.twig, templates/_modules/blocks/publications.twig, templates/_modules/headers/image.twig, templates/_modules/headers/project.twig, templates/_partials/entry/article.twig, templates/_partials/entry/event.twig, templates/_partials/entry/imageColumns.twig, templates/blog/_entry.twig, templates/feed.twig
This PR adds the image transforms.
=> [chore] add image transforms

src/css/main.css
This PR adds `details` expand animation.
=> [chore] add details expand animation

.prettierignore, templates/_macros.twig, templates/projects/index.twig
This PR adds in funding checkbox.
=> [chore] add in funding checkbox

templates/projects/index.twig
This PR changes the projects section.
=> [fix] change projects section

config/project/entryTypes/homepage--711863fc-e341-4c43-b45b-dc33dc3c9c2b.yaml, config/project/project.yaml, src/css/main.css, src/js/components/text-animation.js, src/js/main.js, templates/index.twig
This PR adds the homepage header text animation.
=> [chore] add homepage header text animation

translations/de/site.php
This PR changes the 404 page text.
=> [chore] change 404 page text

templates/blog/_modules/next-reads.twig, translations/de/site.php
This PR updates the more articles translation.
=> [chore] change more articles translation

templates/projects/_category.twig, templates/projects/index.twig
This PR alphabetises the projects.
=> [chore] alphabetise projects

templates/_modules/blocks/expandable-text.twig
This PR fixes the faq text width issues.
=> [fix] Fix faq text width issues

templates/_modules/person-info.twig
This PR fixes the author name / pronoun spacing issue.
=> [fix] fix author name / pronoun spacing issue

src/css/main.css, templates/_modules/blocks/cta-banner.twig, templates/_modules/blocks/text-grid.twig, templates/_modules/date-time.twig, templates/_modules/headers/project.twig, templates/_modules/next-reads.twig, templates/_modules/person-info.twig, templates/_partials/entry/article.twig, templates/_partials/entry/project.twig, templates/_partials/entry/talk.twig, templates/_partials/entry/trend.twig, templates/_rich-text/intro.twig, templates/_rich-text/standard.twig, templates/search/index.twig
This PR fixes the CTA spacing and change line-heights / letter spacing.
=> [chore] [fix] fix cta spacing and change line heights / letter spacing

templates/trends/_entry.twig
This PR fixes the trend text color.
=> [chore] change trend text color

templates/_modules/blocks/link-list.twig, templates/_modules/blocks/publications.twig
This PR fixes the talks and link list title width.
=> [fix] fix talks and link list title width

templates/_modules/headers/simple.twig, templates/_partials/entry/article.twig, templates/_partials/entry/project.twig, templates/projects/_modules/checkbox-filter.twig
This PR increases the project thumbnail width.
=> [chore] increase project thumbnail width

src/css/main.css, templates/_modules/side-heading.twig, templates/_partials/entry/project.twig, templates/projects/_modules/checkbox-filter.twig
=> [chore] add ipad fixes

config/project/fields/nextReads--9c0f58c4-4b28-4aca-b80d-3b370bc38f9e.yaml, config/project/fields/projectNextReads--8c706102-ac71-4054-b178-d266051a8ba8.yaml, config/project/project.yaml
This PR increases the project blog teaser count.
=> [chore] increase project blog teaser count

templates/_modules/main-nav.twig
This PR adds `group-focus-within:z-2` to the main nav.
=> [chore] add group-focus-within:z-2 to nav

src/js/components/main-nav.ts, templates/_modules/main-nav.twig
This PR adds the touch menu open event.
=> [chore] add touch menu open event

src/js/components/main-nav.ts
This PR changes `header` to `links`.
=> [chore] change header to links

src/js/components/main-nav.ts
This PR toggles the classlist for menu-group-open.
=> [chore] toggle classlist for menu-group-open

src/js/components/main-nav.ts, templates/_modules/main-nav.twig
This PR adds `data-link-groups` for `touchstart`.
=> [chore] add link groups touch start

config/project/entryTypes/textGrid--acfeb71e-c3fa-40d8-8b68-3fa03b22cf0a.yaml, config/project/fields/projectLinks--67373325-a234-485a-a635-26dee1e7f325.yaml, config/project/project.yaml, templates/_modules/headers/project.twig
This PR add the project links `linkEmail` field and makes `rows` optional.
=> [chore] add project links linkEmail field

templates/_modules/headers/project.twig
This PR changes the project link order.
=> [chore] change project link order

templates/_modules/cohorts.twig, translations/de/site.php
This PR updates the translations.
=> [chore] update translations

templates/_partials/entry/project.twig
This PR reorders the project categories.
=> [chore] reorder project categories

web/.htaccess
As part of the preparation for the launch.
=> [feature] add htaccess redirects for frb.io domains

config/general.php
=> [chore] limit revsions

templates/_modules/next-reads.twig
This PR changes the `max-w` to `70%`.
=> [chore] change max-w to 70%

config/project/fields/secondaryCaption--5ba16bcf-ba15-4541-978f-c4015909dffb.yaml, config/project/project.yaml, config/project/volumes/uploads--b99ee1fe-b466-49ac-8315-43d2af7587e1.yaml, templates/_partials/entry/imageColumns.twig
This PR adds an image secondary caption.
=> [feature] add image secondary caption

templates/_partials/entry/imageColumns.twig
This PR adds a secondary caption conditional.
=> [chore] add secondary caption conditional

templates/_partials/entry/imageColumns.twig
This PR adds margin-top spacing.
=> [chore] add margin top spacing

templates/_modules/blocks/people-grid.twig
This PR increases the people padding.
=> [chore] increase people padding

templates/_modules/blocks/people-grid.twig
=> [chore] add min-height 470px

templates/_modules/blocks/trend-teasers.twig
This PR adds a `trendsIndex` conditional.
=> [chore] add trends index conditional

README.md
=> [chore] update README

config/knock-knock.php
This PR adds knock knock to production.
=> [chore] add knock knock for production

config/project/fields/textEntryTypes--13a0aaca-3bd8-4653-b163-69738ce277c3.yaml, config/project/project.yaml, templates/search/index.twig
This PR searches for textWithEntryTypes.
=> [chore] search for textWithEntryTypes

templates/feed.twig
This PR removes a typo from the rss feed.
=> [chore] remove typo from rss feed

templates/_layouts/layout.twig
This PR changes the theme color.
=> [chore] change theme color

templates/_partials/entry/charts.twig, templates/_partials/entry/imageColumns.twig
This PR reduces the chart width.
=> [chore] reduce chart width

src/css/main.css, src/js/components/text-animation.js, templates/_layouts/layout.twig
This PR adds header animation tweaks.
=> [chore] add header animation tweaks

templates/projects/_modules/project-filters.twig, templates/projects/index.twig
This PR makes the filter button vertically centered.
=> [chore] make filter button vertically centered

config/knock-knock.php
This PR removes knock knock on production.
=> [chore] remove knock knock on production

web/.htaccess
This PR redirects ptf-prod.frb.io.
=> [chore] redirect ptf-prod.frb.io

templates/_rich-text/columns.twig
This PR reduces the text column.
=> [chore] reduce text column

templates/blog/_entry.twig, templates/trends/_entry.twig
This PR reduces the intro width.
=> [chore] reduce intro width

templates/_rich-text/intro.twig, templates/_rich-text/simple.twig, templates/_rich-text/standard.twig
This PR adds `text-wrap: pretty`.
=> [chore] add text-wrap: pretty

src/css/main.css, templates/_layouts/layout.twig
This PR updates the selection colors.
=> [chore] update selection colors

templates/_modules/headers/project.twig, templates/_modules/lang-switch.twig, templates/_partials/entry/project.twig
=> [chore] polishing

templates/projects/_modules/project-filters.twig
This PR renames the license filter param.
=> [fix] rename license filter param

templates/_modules/cohorts.twig
This PR adds a year groups conditional.
=> [chore] add year groups conditional

config/project/categoryGroups/projectYearGroups--5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a.yaml, config/project/project.yaml, config/project/sections/yearGroupsIndex--df79da8e-b2be-4260-b680-71ef777426bf.yaml, translations/de/site.php
This PR changes the translation and english year groups slug.
=> [chore] change translation and english year groups slug

templates/_modules/blocks/expandable-text.twig
This PR reduces the FAQ icon `stroke-width`.
=> [chore] reduce faq icon stroke-width
